controls:
  - max: 2
    min: -2
    name: point
    perturbation_magnitude: 1e-6
    type: generic_control
    variables:
      - name: x
        initial_guess: [0.8, 1.2, 1.1, 0.9]

objective_functions:
  - name: rosenbrock

install_jobs:
  - name: rosenbrock
    source: jobs/ROSENBROCK

forward_model:
  - rosenbrock \
    --vars point.json \
    --realization r{{ realization }} \
    --out rosenbrock

model:
  realizations: [0, 1, 2, 3, 4]

optimization:
  backend: scipy
  algorithm: slsqp
  perturbation_num: 5
  max_function_evaluations: 30

environment:
  log_level: debug
  random_seed: 1
  simulation_folder: simulations
  output_folder: everest_output/
