controls:
  - initial_guess: 0.25
    max: 2
    min: -2
    name: point
    perturbation_magnitude: 1e-4
    type: generic_control
    variables:
      - name: x
        initial_guess: [0.5, 0.9, 1.3, 1.5, 1.4]

objective_functions:
  - name: rosenbrock

install_jobs:
  - name: rosenbrock
    source: jobs/ROSENBROCK

forward_model:
  - rosenbrock \
    --vars point.json \
    --realization r{{ realization }} \
    --out rosenbrock

model:
  realizations: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

optimization:
  backend: scipy
  algorithm: slsqp
  perturbation_num: 5
  speculative: true
  max_function_evaluations: 30

environment:
  log_level: debug
  random_seed: 1
  simulation_folder: simulations
  output_folder: everest_output/
